### ISSUE TITLE
How to run hiphop without hop.js

### ISSUE THREAD

**Issue by songyahui** [manuel-serrano/hiphop#8]
Hi, 

I read your paper, which says 

"the HipHop.js compiler generates plain JavaScript code that can be used in any server or client Java- Script environment, without Hop.js and without any need for an extra runtime support."

But the installation guidance asks to install hop.js, which is fine, I managed to install, but I find when I run the examples provided from the examples/translator, the page doesn't seems to be reactive. 

But I guess I want to ask that, is there any README to explain how to use hiphop.js without hop? So that I can have a look at the JS code complied by the hiphop compiler. 

Looking forward to your reply!

Thanks,
Yahui

**Comment by manuel-serrano** [comment]
Sorry for this awfully late answer... I suspect that you will no longer be interested but I take the chance:
The new version of HipHop can be used with a bare Node.js installation. Check the 1.3.x branch.

Once again, all my apologizes for the so-late response.
